possible_locations = [
    {"name": "Hogsmeade Haven", "ice_cream_sales": 125, "pizza_sales": 201},
    {"name": "Diagon Alleyville", "ice_cream_sales": 89, "pizza_sales": 154},
    {"name": "Hufflepuff Hamlet", "ice_cream_sales": 47, "pizza_sales": 68},
    {"name": "Ravenclaw Ridge", "ice_cream_sales": 223, "pizza_sales": 12},
    {"name": "Slytherin Springs", "ice_cream_sales": 145, "pizza_sales": 238},
    {"name": "Gryffindor Grove", "ice_cream_sales": 193, "pizza_sales": 99},
    {"name": "Dobby's Den", "ice_cream_sales": 76, "pizza_sales": 122},
    {"name": "Weasley's Wharf", "ice_cream_sales": 32, "pizza_sales": 187},
    {"name": "Snape's Snug", "ice_cream_sales": 204, "pizza_sales": 48},
    {"name": "Hermione's Harbor", "ice_cream_sales": 111, "pizza_sales": 66},
    {"name": "Dumbledore's Domain", "ice_cream_sales": 77, "pizza_sales": 211},
    {"name": "Potter's Point", "ice_cream_sales": 146, "pizza_sales": 97},
    {"name": "Hagrid's Hill", "ice_cream_sales": 52, "pizza_sales": 188},
    {"name": "Luna's Landing", "ice_cream_sales": 133, "pizza_sales": 244},
    {"name": "Malfoy Meadow", "ice_cream_sales": 92, "pizza_sales": 77},
    {"name": "Sirius' Sanctuary", "ice_cream_sales": 155, "pizza_sales": 36},
    {"name": "Bellatrix Bay", "ice_cream_sales": 211, "pizza_sales": 67},
    {"name": "Ron's Roost", "ice_cream_sales": 66, "pizza_sales": 142},
    {"name": "Neville's Nest", "ice_cream_sales": 18, "pizza_sales": 206},
    {"name": "McGonagall's Manor", "ice_cream_sales": 247, "pizza_sales": 54},
    {"name": "Trelawney's Terrace", "ice_cream_sales": 54, "pizza_sales": 173},
    {"name": "Moaning Myrtle's Moor", "ice_cream_sales": 124, "pizza_sales": 220},
    {"name": "Flitwick's Flat", "ice_cream_sales": 213, "pizza_sales": 34},
    {"name": "Fang's Field", "ice_cream_sales": 91, "pizza_sales": 141},
    {"name": "Tonks' Town", "ice_cream_sales": 36, "pizza_sales": 209},
    {"name": "Lucius' Lair", "ice_cream_sales": 251, "pizza_sales": 78},
    {"name": "Rita's Refuge", "ice_cream_sales": 43, "pizza_sales": 157},
    {"name": "Severus' Settlement", "ice_cream_sales": 175, "pizza_sales": 111},
    {"name": "Lupin's Lodge", "ice_cream_sales": 84, "pizza_sales": 56},
    {"name": "Black's Borough", "ice_cream_sales": 140, "pizza_sales": 92},
    {"name": "Winky's Way", "ice_cream_sales": 121, "pizza_sales": 76},
    {"name": "Buckbeak's Bay", "ice_cream_sales": 199, "pizza_sales": 243},
]